services:
  - type: web
    name: mearn-fadjma
    env: node
    branch: main
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    autoDeploy: true
